module.exports = {
  apps: [
    {
      name: 'llm-lab-backend',
      script: 'src/server.js',
      env: {
        NODE_ENV: 'development',
        SVC_PORT: 8787,
        SVC_HOST: '0.0.0.0',
        CALLBACK_BASE_URL: 'http://tts.xserver-krv.ru',
        REMOTE_BAKED_MODEL_PATH: '/app',
        WORKSPACE: process.env.WORKSPACE || '/opt/deepseek-workspace',
        JWT_SECRET: process.env.JWT_SECRET || 'llm-lab-super-secret-key',
      },
      env_production: {
        NODE_ENV: 'production',
        SVC_PORT: 8787,
        SVC_HOST: '0.0.0.0',
        CALLBACK_BASE_URL: 'http://tts.xserver-krv.ru',
        REMOTE_BAKED_MODEL_PATH: '/app',
        WORKSPACE: process.env.WORKSPACE || '/opt/deepseek-workspace',
        JWT_SECRET: process.env.JWT_SECRET || 'llm-lab-super-secret-key',
      },
      watch: ['src'],
      ignore_watch: ['node_modules', '.llm-lab', 'logs'],
      autorestart: true,
      max_memory_restart: '1G',
    },
    {
      name: 'llm-lab-frontend',
      script: 'npm',
      args: 'run web:dev',
      env: {
        NODE_ENV: 'development',
        VITE_API_BASE: 'http://tts.xserver-krv.ru',
      },
      env_production: {
        NODE_ENV: 'production',
        VITE_API_BASE: 'http://tts.xserver-krv.ru',
      },
      autorestart: true,
    },
    {
      name: 'llm-lab-remote-agent',
      script: 'src/agent.js',
      env: {
        NODE_ENV: 'development',
        ORCHESTRATOR_URL: 'http://tts.xserver-krv.ru',
        TRAINER_IMAGE: 'itk-ai-trainer-service:qwen-7b',
        HF_TOKEN: process.env.HF_TOKEN || '',
        OUTPUT_ROOT: '/storage/data/llm-lab/.remote-output',
        CACHE_ROOT: '/storage/data/llm-lab/.remote-cache',
        POLL_INTERVAL: 10000,
        WORKER_NAME: 'xserver-remote-worker',
      },
      env_production: {
        NODE_ENV: 'production',
        ORCHESTRATOR_URL: 'http://tts.xserver-krv.ru',
        TRAINER_IMAGE: 'itk-ai-trainer-service:qwen-7b',
        HF_TOKEN: process.env.HF_TOKEN || '',
        OUTPUT_ROOT: '/storage/data/llm-lab/.remote-output',
        CACHE_ROOT: '/storage/data/llm-lab/.remote-cache',
        POLL_INTERVAL: 10000,
        WORKER_NAME: 'xserver-remote-worker',
      },
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
    },
  ],
};
